# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='response.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0eresponse.proto\"\xa2\x03\n\x08Response\x12\x1c\n\x04type\x18\x01 \x01(\x0e\x32\x0e.Response.Type\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12&\n\tregisters\x18\x03 \x01(\x0b\x32\x13.Response.Registers\x12-\n\rmemory_region\x18\x04 \x01(\x0b\x32\x16.Response.MemoryRegion\x1a\x8d\x01\n\tRegisters\x12\x0b\n\x03PRI\x18\x01 \x01(\x05\x12\x0b\n\x03\x41LT\x18\x02 \x01(\x05\x12\x0b\n\x03\x43OD\x18\x03 \x01(\x05\x12\x0b\n\x03\x44\x41T\x18\x04 \x01(\x05\x12\x0b\n\x03HLW\x18\x05 \x01(\x05\x12\x0b\n\x03HEA\x18\x06 \x01(\x05\x12\x0b\n\x03STP\x18\x07 \x01(\x05\x12\x0b\n\x03STK\x18\x08 \x01(\x05\x12\x0b\n\x03\x46RM\x18\t \x01(\x05\x12\x0b\n\x03\x43IP\x18\n \x01(\x05\x1a=\n\x0cMemoryRegion\x12\x0e\n\x06offset\x18\x01 \x01(\x05\x12\x0e\n\x06length\x18\x02 \x01(\r\x12\r\n\x05\x63\x65lls\x18\x03 \x03(\x05\";\n\x04Type\x12\x0b\n\x07\x46\x41ILURE\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\r\n\tREGISTERS\x10\x02\x12\n\n\x06MEMORY\x10\x03\x62\x06proto3')
)



_RESPONSE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Response.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REGISTERS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEMORY', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=378,
  serialized_end=437,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_TYPE)


_RESPONSE_REGISTERS = _descriptor.Descriptor(
  name='Registers',
  full_name='Response.Registers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PRI', full_name='Response.Registers.PRI', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ALT', full_name='Response.Registers.ALT', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='COD', full_name='Response.Registers.COD', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DAT', full_name='Response.Registers.DAT', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HLW', full_name='Response.Registers.HLW', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HEA', full_name='Response.Registers.HEA', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='STP', full_name='Response.Registers.STP', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='STK', full_name='Response.Registers.STK', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FRM', full_name='Response.Registers.FRM', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CIP', full_name='Response.Registers.CIP', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=313,
)

_RESPONSE_MEMORYREGION = _descriptor.Descriptor(
  name='MemoryRegion',
  full_name='Response.MemoryRegion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='Response.MemoryRegion.offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='Response.MemoryRegion.length', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cells', full_name='Response.MemoryRegion.cells', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=376,
)

_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Response.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='Response.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='registers', full_name='Response.registers', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memory_region', full_name='Response.memory_region', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSE_REGISTERS, _RESPONSE_MEMORYREGION, ],
  enum_types=[
    _RESPONSE_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=437,
)

_RESPONSE_REGISTERS.containing_type = _RESPONSE
_RESPONSE_MEMORYREGION.containing_type = _RESPONSE
_RESPONSE.fields_by_name['type'].enum_type = _RESPONSE_TYPE
_RESPONSE.fields_by_name['registers'].message_type = _RESPONSE_REGISTERS
_RESPONSE.fields_by_name['memory_region'].message_type = _RESPONSE_MEMORYREGION
_RESPONSE_TYPE.containing_type = _RESPONSE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(

  Registers = _reflection.GeneratedProtocolMessageType('Registers', (_message.Message,), dict(
    DESCRIPTOR = _RESPONSE_REGISTERS,
    __module__ = 'response_pb2'
    # @@protoc_insertion_point(class_scope:Response.Registers)
    ))
  ,

  MemoryRegion = _reflection.GeneratedProtocolMessageType('MemoryRegion', (_message.Message,), dict(
    DESCRIPTOR = _RESPONSE_MEMORYREGION,
    __module__ = 'response_pb2'
    # @@protoc_insertion_point(class_scope:Response.MemoryRegion)
    ))
  ,
  DESCRIPTOR = _RESPONSE,
  __module__ = 'response_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  ))
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.Registers)
_sym_db.RegisterMessage(Response.MemoryRegion)


# @@protoc_insertion_point(module_scope)
