# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='task.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\ntask.proto\"\xd7\x03\n\x04Task\x12\x18\n\x04type\x18\x01 \x01(\x0e\x32\n.Task.Type\x12$\n\nbreakpoint\x18\x02 \x01(\x0b\x32\x10.Task.Breakpoint\x12(\n\x0cmemory_query\x18\x03 \x01(\x0b\x32\x12.Task.MemoryRegion\x1a\x99\x01\n\nBreakpoint\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1f.Task.Breakpoint.BreakpointType\x12\x1b\n\x13instruction_pointer\x18\x02 \x01(\x05\x12\x0c\n\x04\x66ile\x18\x03 \x01(\t\x12\x0c\n\x04line\x18\x04 \x01(\r\"#\n\x0e\x42reakpointType\x12\x07\n\x03\x43IP\x10\x00\x12\x08\n\x04LINE\x10\x01\x1a.\n\x0cMemoryRegion\x12\x0e\n\x06offset\x18\x01 \x01(\x05\x12\x0e\n\x06length\x18\x02 \x01(\x05\"\x98\x01\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03RUN\x10\x01\x12\x08\n\x04STOP\x10\x02\x12\x0f\n\x0bSTEP_SINGLE\x10\x03\x12\r\n\tSTEP_LINE\x10\x04\x12\x12\n\x0e\x42REAKPOINT_ADD\x10\x05\x12\x15\n\x11\x42REAKPOINT_REMOVE\x10\x06\x12\x13\n\x0fQUERY_REGISTERS\x10\x07\x12\x10\n\x0cQUERY_MEMORY\x10\x08\x62\x06proto3')
)



_TASK_BREAKPOINT_BREAKPOINTTYPE = _descriptor.EnumDescriptor(
  name='BreakpointType',
  full_name='Task.Breakpoint.BreakpointType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CIP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LINE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=248,
  serialized_end=283,
)
_sym_db.RegisterEnumDescriptor(_TASK_BREAKPOINT_BREAKPOINTTYPE)

_TASK_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='Task.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STEP_SINGLE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STEP_LINE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BREAKPOINT_ADD', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BREAKPOINT_REMOVE', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUERY_REGISTERS', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUERY_MEMORY', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=334,
  serialized_end=486,
)
_sym_db.RegisterEnumDescriptor(_TASK_TYPE)


_TASK_BREAKPOINT = _descriptor.Descriptor(
  name='Breakpoint',
  full_name='Task.Breakpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Task.Breakpoint.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instruction_pointer', full_name='Task.Breakpoint.instruction_pointer', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file', full_name='Task.Breakpoint.file', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='line', full_name='Task.Breakpoint.line', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TASK_BREAKPOINT_BREAKPOINTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=283,
)

_TASK_MEMORYREGION = _descriptor.Descriptor(
  name='MemoryRegion',
  full_name='Task.MemoryRegion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='Task.MemoryRegion.offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='Task.MemoryRegion.length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=331,
)

_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Task.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='breakpoint', full_name='Task.breakpoint', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memory_query', full_name='Task.memory_query', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TASK_BREAKPOINT, _TASK_MEMORYREGION, ],
  enum_types=[
    _TASK_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=486,
)

_TASK_BREAKPOINT.fields_by_name['type'].enum_type = _TASK_BREAKPOINT_BREAKPOINTTYPE
_TASK_BREAKPOINT.containing_type = _TASK
_TASK_BREAKPOINT_BREAKPOINTTYPE.containing_type = _TASK_BREAKPOINT
_TASK_MEMORYREGION.containing_type = _TASK
_TASK.fields_by_name['type'].enum_type = _TASK_TYPE
_TASK.fields_by_name['breakpoint'].message_type = _TASK_BREAKPOINT
_TASK.fields_by_name['memory_query'].message_type = _TASK_MEMORYREGION
_TASK_TYPE.containing_type = _TASK
DESCRIPTOR.message_types_by_name['Task'] = _TASK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), dict(

  Breakpoint = _reflection.GeneratedProtocolMessageType('Breakpoint', (_message.Message,), dict(
    DESCRIPTOR = _TASK_BREAKPOINT,
    __module__ = 'task_pb2'
    # @@protoc_insertion_point(class_scope:Task.Breakpoint)
    ))
  ,

  MemoryRegion = _reflection.GeneratedProtocolMessageType('MemoryRegion', (_message.Message,), dict(
    DESCRIPTOR = _TASK_MEMORYREGION,
    __module__ = 'task_pb2'
    # @@protoc_insertion_point(class_scope:Task.MemoryRegion)
    ))
  ,
  DESCRIPTOR = _TASK,
  __module__ = 'task_pb2'
  # @@protoc_insertion_point(class_scope:Task)
  ))
_sym_db.RegisterMessage(Task)
_sym_db.RegisterMessage(Task.Breakpoint)
_sym_db.RegisterMessage(Task.MemoryRegion)


# @@protoc_insertion_point(module_scope)
